-- Backfill testament and book columns for existing spreads
-- Run this in Supabase SQL Editor

-- Map spread_code prefixes to book names and testaments
UPDATE grahams_devotional_spreads SET
  testament = CASE 
    -- Old Testament books
    WHEN spread_code LIKE 'GEN-%' THEN 'OT'
    WHEN spread_code LIKE 'EXO-%' THEN 'OT'
    WHEN spread_code LIKE 'LEV-%' THEN 'OT'
    WHEN spread_code LIKE 'NUM-%' THEN 'OT'
    WHEN spread_code LIKE 'DEU-%' THEN 'OT'
    WHEN spread_code LIKE 'JOS-%' THEN 'OT'
    WHEN spread_code LIKE 'JDG-%' THEN 'OT'
    WHEN spread_code LIKE 'RUT-%' THEN 'OT'
    WHEN spread_code LIKE '1SA-%' THEN 'OT'
    WHEN spread_code LIKE '2SA-%' THEN 'OT'
    WHEN spread_code LIKE '1KI-%' THEN 'OT'
    WHEN spread_code LIKE '2KI-%' THEN 'OT'
    WHEN spread_code LIKE '1CH-%' THEN 'OT'
    WHEN spread_code LIKE '2CH-%' THEN 'OT'
    WHEN spread_code LIKE 'EZR-%' THEN 'OT'
    WHEN spread_code LIKE 'NEH-%' THEN 'OT'
    WHEN spread_code LIKE 'EST-%' THEN 'OT'
    WHEN spread_code LIKE 'JOB-%' THEN 'OT'
    WHEN spread_code LIKE 'PSA-%' THEN 'OT'
    WHEN spread_code LIKE 'PRO-%' THEN 'OT'
    WHEN spread_code LIKE 'ECC-%' THEN 'OT'
    WHEN spread_code LIKE 'SNG-%' THEN 'OT'
    WHEN spread_code LIKE 'ISA-%' THEN 'OT'
    WHEN spread_code LIKE 'JER-%' THEN 'OT'
    WHEN spread_code LIKE 'LAM-%' THEN 'OT'
    WHEN spread_code LIKE 'EZK-%' THEN 'OT'
    WHEN spread_code LIKE 'DAN-%' THEN 'OT'
    WHEN spread_code LIKE 'HOS-%' THEN 'OT'
    WHEN spread_code LIKE 'JOL-%' THEN 'OT'
    WHEN spread_code LIKE 'AMO-%' THEN 'OT'
    WHEN spread_code LIKE 'OBA-%' THEN 'OT'
    WHEN spread_code LIKE 'JON-%' THEN 'OT'
    WHEN spread_code LIKE 'MIC-%' THEN 'OT'
    WHEN spread_code LIKE 'NAM-%' THEN 'OT'
    WHEN spread_code LIKE 'HAB-%' THEN 'OT'
    WHEN spread_code LIKE 'ZEP-%' THEN 'OT'
    WHEN spread_code LIKE 'HAG-%' THEN 'OT'
    WHEN spread_code LIKE 'ZEC-%' THEN 'OT'
    WHEN spread_code LIKE 'MAL-%' THEN 'OT'
    -- New Testament books
    WHEN spread_code LIKE 'MAT-%' THEN 'NT'
    WHEN spread_code LIKE 'MRK-%' THEN 'NT'
    WHEN spread_code LIKE 'LUK-%' THEN 'NT'
    WHEN spread_code LIKE 'JHN-%' THEN 'NT'
    WHEN spread_code LIKE 'ACT-%' THEN 'NT'
    WHEN spread_code LIKE 'ROM-%' THEN 'NT'
    WHEN spread_code LIKE '1CO-%' THEN 'NT'
    WHEN spread_code LIKE '2CO-%' THEN 'NT'
    WHEN spread_code LIKE 'GAL-%' THEN 'NT'
    WHEN spread_code LIKE 'EPH-%' THEN 'NT'
    WHEN spread_code LIKE 'PHP-%' THEN 'NT'
    WHEN spread_code LIKE 'COL-%' THEN 'NT'
    WHEN spread_code LIKE '1TH-%' THEN 'NT'
    WHEN spread_code LIKE '2TH-%' THEN 'NT'
    WHEN spread_code LIKE '1TI-%' THEN 'NT'
    WHEN spread_code LIKE '2TI-%' THEN 'NT'
    WHEN spread_code LIKE 'TIT-%' THEN 'NT'
    WHEN spread_code LIKE 'PHM-%' THEN 'NT'
    WHEN spread_code LIKE 'HEB-%' THEN 'NT'
    WHEN spread_code LIKE 'JAS-%' THEN 'NT'
    WHEN spread_code LIKE '1PE-%' THEN 'NT'
    WHEN spread_code LIKE '2PE-%' THEN 'NT'
    WHEN spread_code LIKE '1JN-%' THEN 'NT'
    WHEN spread_code LIKE '2JN-%' THEN 'NT'
    WHEN spread_code LIKE '3JN-%' THEN 'NT'
    WHEN spread_code LIKE 'JUD-%' THEN 'NT'
    WHEN spread_code LIKE 'REV-%' THEN 'NT'
    ELSE testament -- Keep existing value if no match
  END,
  book = CASE 
    -- Old Testament books
    WHEN spread_code LIKE 'GEN-%' THEN 'Genesis'
    WHEN spread_code LIKE 'EXO-%' THEN 'Exodus'
    WHEN spread_code LIKE 'LEV-%' THEN 'Leviticus'
    WHEN spread_code LIKE 'NUM-%' THEN 'Numbers'
    WHEN spread_code LIKE 'DEU-%' THEN 'Deuteronomy'
    WHEN spread_code LIKE 'JOS-%' THEN 'Joshua'
    WHEN spread_code LIKE 'JDG-%' THEN 'Judges'
    WHEN spread_code LIKE 'RUT-%' THEN 'Ruth'
    WHEN spread_code LIKE '1SA-%' THEN '1 Samuel'
    WHEN spread_code LIKE '2SA-%' THEN '2 Samuel'
    WHEN spread_code LIKE '1KI-%' THEN '1 Kings'
    WHEN spread_code LIKE '2KI-%' THEN '2 Kings'
    WHEN spread_code LIKE '1CH-%' THEN '1 Chronicles'
    WHEN spread_code LIKE '2CH-%' THEN '2 Chronicles'
    WHEN spread_code LIKE 'EZR-%' THEN 'Ezra'
    WHEN spread_code LIKE 'NEH-%' THEN 'Nehemiah'
    WHEN spread_code LIKE 'EST-%' THEN 'Esther'
    WHEN spread_code LIKE 'JOB-%' THEN 'Job'
    WHEN spread_code LIKE 'PSA-%' THEN 'Psalms'
    WHEN spread_code LIKE 'PRO-%' THEN 'Proverbs'
    WHEN spread_code LIKE 'ECC-%' THEN 'Ecclesiastes'
    WHEN spread_code LIKE 'SNG-%' THEN 'Song of Solomon'
    WHEN spread_code LIKE 'ISA-%' THEN 'Isaiah'
    WHEN spread_code LIKE 'JER-%' THEN 'Jeremiah'
    WHEN spread_code LIKE 'LAM-%' THEN 'Lamentations'
    WHEN spread_code LIKE 'EZK-%' THEN 'Ezekiel'
    WHEN spread_code LIKE 'DAN-%' THEN 'Daniel'
    WHEN spread_code LIKE 'HOS-%' THEN 'Hosea'
    WHEN spread_code LIKE 'JOL-%' THEN 'Joel'
    WHEN spread_code LIKE 'AMO-%' THEN 'Amos'
    WHEN spread_code LIKE 'OBA-%' THEN 'Obadiah'
    WHEN spread_code LIKE 'JON-%' THEN 'Jonah'
    WHEN spread_code LIKE 'MIC-%' THEN 'Micah'
    WHEN spread_code LIKE 'NAM-%' THEN 'Nahum'
    WHEN spread_code LIKE 'HAB-%' THEN 'Habakkuk'
    WHEN spread_code LIKE 'ZEP-%' THEN 'Zephaniah'
    WHEN spread_code LIKE 'HAG-%' THEN 'Haggai'
    WHEN spread_code LIKE 'ZEC-%' THEN 'Zechariah'
    WHEN spread_code LIKE 'MAL-%' THEN 'Malachi'
    -- New Testament books
    WHEN spread_code LIKE 'MAT-%' THEN 'Matthew'
    WHEN spread_code LIKE 'MRK-%' THEN 'Mark'
    WHEN spread_code LIKE 'LUK-%' THEN 'Luke'
    WHEN spread_code LIKE 'JHN-%' THEN 'John'
    WHEN spread_code LIKE 'ACT-%' THEN 'Acts'
    WHEN spread_code LIKE 'ROM-%' THEN 'Romans'
    WHEN spread_code LIKE '1CO-%' THEN '1 Corinthians'
    WHEN spread_code LIKE '2CO-%' THEN '2 Corinthians'
    WHEN spread_code LIKE 'GAL-%' THEN 'Galatians'
    WHEN spread_code LIKE 'EPH-%' THEN 'Ephesians'
    WHEN spread_code LIKE 'PHP-%' THEN 'Philippians'
    WHEN spread_code LIKE 'COL-%' THEN 'Colossians'
    WHEN spread_code LIKE '1TH-%' THEN '1 Thessalonians'
    WHEN spread_code LIKE '2TH-%' THEN '2 Thessalonians'
    WHEN spread_code LIKE '1TI-%' THEN '1 Timothy'
    WHEN spread_code LIKE '2TI-%' THEN '2 Timothy'
    WHEN spread_code LIKE 'TIT-%' THEN 'Titus'
    WHEN spread_code LIKE 'PHM-%' THEN 'Philemon'
    WHEN spread_code LIKE 'HEB-%' THEN 'Hebrews'
    WHEN spread_code LIKE 'JAS-%' THEN 'James'
    WHEN spread_code LIKE '1PE-%' THEN '1 Peter'
    WHEN spread_code LIKE '2PE-%' THEN '2 Peter'
    WHEN spread_code LIKE '1JN-%' THEN '1 John'
    WHEN spread_code LIKE '2JN-%' THEN '2 John'
    WHEN spread_code LIKE '3JN-%' THEN '3 John'
    WHEN spread_code LIKE 'JUD-%' THEN 'Jude'
    WHEN spread_code LIKE 'REV-%' THEN 'Revelation'
    ELSE book -- Keep existing value if no match
  END
WHERE testament IS NULL OR book IS NULL;

-- Verify the update
SELECT testament, book, COUNT(*) as count 
FROM grahams_devotional_spreads 
GROUP BY testament, book 
ORDER BY testament, book;
